### ISSUE TITLE
What's the purpose of the reference to $JETTY_BASE in debugger setup?

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/openjdk-runtime#33]
setup-env.bash has this block of code to set up the Stackdriver Debugger agent. The line that I'm confused about is `DBG_AGENT="$( RUNTIME_DIR=$JETTY_BASE /opt/cdbg/format-env-appengine-vm.sh )"`. Why are we referencing `$JETTY_BASE` here? It wouldn't be defined for a vanilla Java app.
```shell
DBG_AGENT=
if isTrue "${DBG_ENABLE:=$( if [[ -z ${CDBG_DISABLE} ]] ; then echo true; else echo false ; fi )}" ; then
  if [[ "$GAE_PARTITION" = "dev" ]]; then
    echo "Running locally and DBG_ENABLE is set, enabling standard Java debugger agent"
    DBG_AGENT="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=${DBG_PORT:=5005}"
  else
    unset CDBG_DISABLE
    DBG_AGENT="$( RUNTIME_DIR=$JETTY_BASE /opt/cdbg/format-env-appengine-vm.sh )"
  fi
fi
```

**Comment by gregw** [comment]
the formate-env-appengine-vm.sh script contains the following:
```
APP_WEB_INF_DIR="${RUNTIME_DIR}/webapps/root/WEB-INF"
CDBG_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

ARGS="-agentpath:${CDBG_ROOT}/cdbg_java_agent.so="
ARGS+="--log_dir=/var/log/app_engine"
ARGS+=",--logtostderr=false"
ARGS+=",--cdbg_extra_class_path=${APP_WEB_INF_DIR}/classes:${APP_WEB_INF_DIR}/lib"
```

So using `$JETTY_BASE` is there to help it find the additional classpath entries from the webapp. 

This should probably be changed to either:
- leave `RUNTIME_DIR` undefined and only define it in `jetty-runtime` or equivalent runtime.
- define it in terms of a container neutral term that is then only defined in  `jetty-runtime` or equivalent runtime.

Eitherway,  it would be good to get the `format-env-appengine-vm.sh` script updated so that the `--cdbg_extra_class_path` option is only set if `RUNTIME_DIR` is defined and contains WEB-INF/lib|classes directories.  Potentially it should search for more than one context being deployed.    Better yet, it would allow the derived image to set the extra classpath as an ENV variable rather than assuming a traditional WEB-INF layout.

**Comment by meltsufin** [comment]
Looking at the [official docs for setting up the Debugger on GCE](https://cloud.google.com/debugger/docs/setting-up-on-compute-engine), the `format-env-appengine-vm.sh` is not even mentioned.

We need to find out if using this script is till the recommended approach for runtimes that are meant to be portable to GCE and GKE.

In any case, your suggestion to only define `RUNTIME_DIR` in the jetty image, makes sense.
